name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git
        uses: actions/checkout@v1

      - name: Setup yarn
        uses: actions/setup-node@v1

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build
        run: yarn build

      - name: Bundle size check
        run: yarn size

      - name: Run tests
        run: yarn test:coverage

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v2.4.0
        with:
          coverageLocations: '/coverage/lcov.info'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TOKEN }}
