name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build
        run: yarn build

      - name: Bundle size check
        run: yarn size

      - name: Run Tests & Publish code coverage
        uses: paambaati/codeclimate-action@v2.4.0
        with:
          coverageCommand: yarn test:ci:coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TOKEN }}
